# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_data', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
