# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160319_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
