# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
