# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_temperature_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
