# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
