# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
    ]
