# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160319_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='timestamp',
        ),
    ]
