# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_temperature_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
