# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='location',
        ),
        migrations.AddField(
            model_name='temperature',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
