# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
