# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160319_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='location',
        ),
    ]
